#pragma once

#define PMODDER_DEVICE	0x8000

#define PMODDER_UNPROTECT		CTL_CODE(PMODDER_DEVICE, 0x800, METHOD_NEITHER, FILE_ANY_ACCESS)
#define PMODDER_PROTECT			CTL_CODE(PMODDER_DEVICE, 0x801, METHOD_NEITHER, FILE_ANY_ACCESS)